Fix failure to load native module on NixOS
Saw this stack trace in my NixOS deployment

 /nix/store/arri1yg3iyx67vjb6971l1dkggv7lbq8-paseo-0.3.0-beta.2/lib/paseo/packages/server/node_modules/node-pty/lib/utils.js:36
     throw new Error("Failed to load native module: ".concat(name, ".node, checked: ").concat(dirs.join(', '), ": ").concat(lastError));
           ^
 Error: Failed to load native module: pty.node, checked: build/Release, build/Debug, prebuilds/linux-x64: Error: Cannot find module './prebuilds/linux-x64/pty.node'
 Require stack:
 - /nix/store/arri1yg3iyx67vjb6971l1dkggv7lbq8-paseo-0.3.0-beta.2/lib/paseo/packages/server/node_modules/node-pty/lib/utils.js
 - /nix/store/arri1yg3iyx67vjb6971l1dkggv7lbq8-paseo-0.3.0-beta.2/lib/paseo/packages/server/node_modules/node-pty/lib/index.js
     at loadNativeModule (/nix/store/arri1yg3iyx67vjb6971l1dkggv7lbq8-paseo-0.3.0-beta.2/lib/paseo/packages/server/node_modules/node-pty/lib/utils.js:36:11)
     at Object.<anonymous> (/nix/store/arri1yg3iyx67vjb6971l1dkggv7lbq8-paseo-0.3.0-beta.2/lib/paseo/packages/server/node_modules/node-pty/lib/unixTerminal.js:29:43)
     at Module._compile (node:internal/modules/cjs/loader:1705:14)
     at Object..js (node:internal/modules/cjs/loader:1838:10)
     at Module.load (node:internal/modules/cjs/loader:1441:32)
     at Function._load (node:internal/modules/cjs/loader:1263:12)
     at TracingChannel.traceSync (node:diagnostics_channel:328:14)
     at wrapModuleLoad (node:internal/modules/cjs/loader:237:24)
     at Module.require (node:internal/modules/cjs/loader:1463:12)
     at require (node:internal/modules/helpers:147:16)
 Node.js v22.22.1